export const DEVNET_RPC_ENDPOINT = process.env.NEXT_PUBLIC_HELIUS_DEVNET;

export const MAINNET_RPC_ENDPOINT = process.env.NEXT_PUBLIC_HELIUS_MAINNET;

export const TESTNET_RPC_ENDPOINT = 'http://127.0.0.1:8899';

export const CURRENT_RPC_ENDPOINT = DEVNET_RPC_ENDPOINT;
